module.exports = {
    "LEFT_CONTROL": "control",
    "LEFT_SHIFT": "shift",
    "LEFT_ALT": "alt",
    "LEFT_WIN": "win",
    "RIGHT_SHIFT": "right_shift",
    "RIGHT_ALT": "right_alt",

    "ESCAPE": "escape",
    "F1": "f1",
    "F2": "f2",
    "F3": "f3",
    "F4": "f4",
    "F5": "f5",
    "F6": "f6",
    "F7": "f7",
    "F8": "f8",
    "F9": "f9",
    "F10": "f10",
    "F11": "f11",
    "F12": "f12",
    "PAUSE": null,
    "PRINT_SCREEN": null,
    "INSERT": "insert",
    "DELETE": "delete",

    "²": "oem_7",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "0": "0",
    "DEGREE": "]",
    "PLUS": "=",
    "BACKSPACE": "backspace",

    "TAB": "tab",
    "A": "a",
    "Z": "z",
    "E": "e",
    "R": "r",
    "T": "t",
    "Y": "y",
    "U": "u",
    "I": "i",
    "O": "o",
    "P": "p",
    "CIRCUMFLEX": "oem_6",
    "DOLLAR": "oem_1",
    "ASTERISK": "oem_5",

    "CAPS_LOCK": "caps_lock",
    "Q": "q",
    "S": "s",
    "D": "d",
    "F": "f",
    "G": "g",
    "H": "h",
    "J": "j",
    "K": "k",
    "L": "l",
    "M": "m",
    "ù": "oem_3",
    "ENTER": "enter",

    "ANGLE_BRACKET": "oem_102",
    "W": "w",
    "X": "x",
    "C": "c",
    "V": "v",
    "B": "b",
    "N": "n",
    "COMMA": ",",
    "SEMICOLON": ";",
    "COLON": "oem_2",
    "EXCLAMATION": "oem_8",

    "SPACE": "space",
    "RIGHT_ARROW": "right",
    "HOME": "home",
    "UP_ARROW": "up",
    "PAGE_UP": "pageup",
    "DOWN_ARROW": "down",
    "PAGE_DOWN": "pagedown",
    "LEFT_ARROW": "left",
    "END": "end",

    "AC_HOME": "home",
    "AC_SEARCH": null,
    "AC_BACK": null,

    "PREVIOUS_TRACK": "audio_prev",
    "NEXT_TRACK": "audio_next",
    "POWER": null,
    "PLAY_PAUSE": "audio_play",
    "VOLUME_UP": "audio_vol_up",
    "VOLUME_DOWN": "audio_vol_down"
};
